// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQcjfIFe_kqj8Rm1AvQzQBjT22Fu2Tops',
    appId: '1:763603420337:web:468acec217af7a8931ce90',
    messagingSenderId: '763603420337',
    projectId: 'ahmedzoalashop',
    authDomain: 'ahmedzoalashop.firebaseapp.com',
    storageBucket: 'ahmedzoalashop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATfaUxnv6vIG-ErdO6H7PdpE9r7Rx732o',
    appId: '1:763603420337:android:c108f5b6d8c0477d31ce90',
    messagingSenderId: '763603420337',
    projectId: 'ahmedzoalashop',
    storageBucket: 'ahmedzoalashop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa2LaF47Hc5q25K4003cmoyUEubTpFxK4',
    appId: '1:763603420337:ios:cd214e5e5fcc332731ce90',
    messagingSenderId: '763603420337',
    projectId: 'ahmedzoalashop',
    storageBucket: 'ahmedzoalashop.appspot.com',
    iosBundleId: 'com.example.ahmedZoalaShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa2LaF47Hc5q25K4003cmoyUEubTpFxK4',
    appId: '1:763603420337:ios:974578d6cb606eb031ce90',
    messagingSenderId: '763603420337',
    projectId: 'ahmedzoalashop',
    storageBucket: 'ahmedzoalashop.appspot.com',
    iosBundleId: 'com.example.ahmedZoalaShop.RunnerTests',
  );
}
